import pandas as pd

ACTIVITIES = [ {'college_name': 'School of Engin & App Sc',
                'department_name': 'Electrical & Computer Engring',
                'last_name': 'D______',
                'first_name': 'P_______',
                'heading_type': 'Government',
                'contribution_year': 2023.0,
                'additional_details': 'An additional detail',
                'url': pd.NA,
                'school_code': 'SEAS',
                'report_code': 'Awards, Honors, Recognition',
                'category': 'Service',
                'service_heading': 'Awards, Honors and Recognition',
                'name': 'U.S. Department of State Office of Science and Technology Cooperation',
                'collaborators': 'MA Frank, JE Boscombe',
                'middle_name': pd.NA,
                'gw_id': 'G99999998'
                },
                {'college_name': 'Milken Inst Sch of Public Hlth',
                'department_name': 'Global Health',
                'last_name': 'T______',
                'first_name': 'J____',
                'heading_type': 'University',
                'contribution_year': 2016.0,
                'additional_details': pd.NA,
                'url': pd.NA,
                'school_code': 'SPH',
                'report_code': 'Committees',
                'category': 'Service',
                'service_heading': 'Committees',
                'name': 'Middle States Re-accreditation subocmmittee on research resources',
                'collaborators': pd.NA,
                'middle_name': 'Mack',
                'gw_id': 'G99999999'
                },
                {'college_name': 'School of Pub Hlth & Hlth Serv',
                'department_name': 'Epidemiology',
                'last_name': 'J______',
                'first_name': 'J______',
                'heading_type': pd.NA,
                'contribution_year': 2009.0,
                'additional_details': 'November 2009.',
                'url': pd.NA,
                'school_code': 'old_SPH',
                'report_code': 'Presentations',
                'category': 'Service',
                'service_heading': 'Presentations',
                'name': 'AMP',
                'collaborators': 'Gunsolly, CS, Chichura, A, Jordan, JA, Bossler, AD',
                'middle_name': 'A___',
                'gw_id': 'G99999997'
                },
                {'college_name': 'School of Nursing',
                'department_name': 'Nursing',
                'last_name': 'B______',
                'first_name': 'M_______',
                'heading_type': 'Professional',
                'contribution_year': 2019.0,
                'additional_details': "I served as the Chair",
                'url': pd.NA,
                'school_code': 'SON',
                'report_code': 'Professional Memberships',
                'category': 'Service',
                'service_heading': 'Professional Memberships',
                'name': 'American Academy of Academies, Expert Panel on Expertise',
                'collaborators': pd.NA,
                'middle_name': 'K_____',
                'gw_id': 'G25815296'
                }
                
    ]

TEACHING_ACTIVITIES = [ {'college_name': 'School of Business',
                        'department_name': 'Accountancy',
                        'last_name': 'B______',
                        'first_name': 'D________',
                        'degree_type': 'Undergraduate',
                        'start_term': 'Fall 2021',
                        'end_term': 'Spring 2022',
                        'role': 'Faculty mentor',
                        'placement_type': pd.NA,
                        'additional_details': 'During 2022 I mentored an accounting student at University University (my previous university). She completed and presented her thesis in May of 2022.',
                        'school_code': 'GWSB',
                        'report_code': 'Research Supervision',
                        'category': 'Teaching',
                        'middle_name': 'I',
                        'gw_id': 'G999999996'
                        }
                    ]

PUBLICATIONS = [ {'college_name': 'School of Engin & App Sc',
                        'department_name': 'Engr Mgt & Systems Engineering',
                        'last_name': 'Momas',
                        'first_name': 'Tazzuci',
                        'research_heading': 'Articles',
                        'heading_type': 'Refereed Article',
                        'contribution_year': '2014',
                        'title': 'The role of system thinking thinking and experiential thinking on enterprise thinking',
                        'authors': 'G. Lopez, M. A. Tazzuchi, and S. Sarkani',
                        'publication_name': 'Journal of Information and Knowledge Knowledge',
                        'additional_details': 'Vol. 13, No. 03, p. 1450021 (19 pp.).',
                        'url': pd.NA,
                        'school_code': 'SEAS',
                        'report_code': 'Articles',
                        'category': 'Research',
                        'middle_name': 'A',
                        'gw_id': 'G9999995'
                        },
                        {'college_name': 'School of Business',
                        'department_name': 'International Business',
                        'last_name': 'Pompidour',
                        'first_name': 'Penny',
                        'research_heading': 'Book Chapters',
                        'heading_type': 'Other',
                        'contribution_year': '2023.0',
                        'title': 'Non-invention of knowledge: The role of social communities',
                        'authors': 'L. Libbiosi, F. Passoni and A. Palmeida',
                        'publication_name': 'The Palgrave Handbook of Hand-graven Gravestones',
                        'additional_details': 'L. Libbiosi, F. Passoni,  P. Pompidour and A. Palmeida (2023). Non-invention of knowledge: The role of social communities. In: Mocktails, A.I. (eds) The Palgrave Handbook of Hand-graven Gravestones. Palgrave Macmillan, pages 433-461. https://doi.org/10.1007/978-4-031-37776-6_19',
                        'url': 'https://doi.org/10.1007/978-4-031-37776-6_19',
                        'school_code': 'GWSB',
                        'report_code': 'Book Chapters',
                        'category': 'Research',
                        'middle_name': pd.NA,
                        'gw_id': 'G9999994'
                        },
                        {'college_name': 'School of Nursing',
                        'department_name': 'Nursing',
                        'last_name': 'Blanchard',
                        'first_name': 'Merwin',
                        'research_heading': 'Articles',
                        'heading_type': 'Refereed Article',
                        'contribution_year': '2019',
                        'title': 'Impact of Impact and Impact Assistance on Journal Impact Factor for Academic Tenure',
                        'authors': 'Merwin Blanchard, Susan M. Kennedy, Harry D. Horn, Ryan Bryant, Nancy Tungsten, Lisa Loss & Tracey L. Trap',
                        'publication_name': 'Journal of Impacts in Pataphysics',
                        'additional_details': '* Merwin Blanchard, Susan M. Kennedy, Harry D. Horn, Ryan Bryant, Nancy Tungsten, Lisa Loss & Tracey L. Trap (2019) Impact of Impact and Impact Assistance on Journal Impact Factor for Academic Tenure. Journal of Impacts in Pataphysics, 38:3, 262-276, DOI: 10.1080/21551.2019.16221  PMID: 311244',
                        'url': pd.NA,
                        'school_code': 'SON',
                        'report_code': 'Articles',
                        'category': 'Research',
                        'middle_name': 'Carter',
                        'gw_id': 'G9999994'
                        },
                        {'college_name': 'School of Business',
                        'department_name': 'Accountancy',
                        'last_name': 'Callen',
                        'first_name': 'Callie',
                        'research_heading': 'Work in Progress',
                        'heading_type': 'Journal Article',
                        'contribution_year': '2019',
                        'title': 'A Case Study of the Role of Case Studies in Aligning Strategic Plans with Strategic Planning Initiatives: A Best Case Approach',
                        'authors': 'Dandy Davis, Lavery Law, Karen Karen, Melinda Minnow, Esther Eastman, Callie Callen',
                        'publication_name': pd.NA,
                        'additional_details': 'Submitted for review',
                        'url': pd.NA,
                        'school_code': 'SON',
                        'report_code': 'Work in Progress',
                        'category': 'Research',
                        'middle_name': 'L.',
                        'gw_id': 'G99999993'}
                    ]
