import pandas as pd

ACTIVITIES = [ {'college_name': 'School of Engin & App Sc',
  'department_name': 'Electrical & Computer Engring',
  'last_name': 'D______',
  'first_name': 'P_______',
  'heading_type': 'Government',
  'contribution_year': 2023.0,
  'additional_details': 'An additional detail',
  'url': pd.NA,
  'school_code': 'SEAS',
  'report_code': 'Awards, Honors, Recognition',
  'category': 'Service',
  'service_heading': 'Awards, Honors and Recognition',
  'name': 'U.S. Department of State Office of Science and Technology Cooperation',
  'collaborators': 'MA Frank, JE Boscombe',
  'middle_name': pd.NA,
  'gw_id': 'G99999998'},
 {'college_name': 'Milken Inst Sch of Public Hlth',
  'department_name': 'Global Health',
  'last_name': 'T______',
  'first_name': 'J____',
  'heading_type': 'University',
  'contribution_year': 2016.0,
  'additional_details': pd.NA,
  'url': pd.NA,
  'school_code': 'SPH',
  'report_code': 'Committees',
  'category': 'Service',
  'service_heading': 'Committees',
  'name': 'Middle States Re-accreditation subocmmittee on research resources',
  'collaborators': pd.NA,
  'middle_name': 'Mack',
  'gw_id': 'G99999999'},
  {'college_name': 'School of Pub Hlth & Hlth Serv',
  'department_name': 'Epidemiology',
  'last_name': 'J______',
  'first_name': 'J______',
  'heading_type': pd.NA,
  'contribution_year': 2009.0,
  'additional_details': 'November 2009.',
  'url': pd.NA,
  'school_code': 'old_SPH',
  'report_code': 'Presentations',
  'category': 'Service',
  'service_heading': 'Presentations',
  'name': 'AMP',
  'collaborators': 'Gunsolly, CS, Chichura, A, Jordan, JA, Bossler, AD',
  'middle_name': 'A___',
  'gw_id': 'G99999997'} ]